using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CiviLanka.API.Models.Infrastructure
{
    /// <summary>
    /// Persists the structured risk assessment and degradation prediction
    /// generated by the AssetRiskPredictionAgent for an infrastructure asset.
    /// Supports historical versioning and decision traceability.
    /// </summary>
    public class AssetRiskAnalysis
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        [Required]
        [MaxLength(20)]
        public string AssetId { get; set; } = string.Empty;

        [ForeignKey(nameof(AssetId))]
        public InfrastructureAsset? Asset { get; set; }

        /// <summary>LOW | MEDIUM | HIGH | CRITICAL</summary>
        [Required]
        [MaxLength(20)]
        public string RiskLevel { get; set; } = "MEDIUM";

        /// <summary>Calculated risk score from 0 to 100.</summary>
        public int RiskScore { get; set; }

        /// <summary>Confidence score from the AI model (0.0 to 1.0).</summary>
        public double Confidence { get; set; }

        /// <summary>Assessment: Good | Satisfactory | Deteriorating | Critical</summary>
        [MaxLength(50)]
        public string ConditionAssessment { get; set; } = "Deteriorating";

        /// <summary>Failure likelihood: Low | Moderate | High | Imminent</summary>
        [MaxLength(30)]
        public string FailureLikelihood { get; set; } = "Moderate";

        /// <summary>Reasoning explanation from the model.</summary>
        public string Reason { get; set; } = string.Empty;

        /// <summary>Recommended frequency: Weekly | Bi-Weekly | Monthly | Quarterly | Annually</summary>
        [MaxLength(50)]
        public string RecommendedInspectionFrequency { get; set; } = "Monthly";

        /// <summary>Actionable recommendation for municipal engineers.</summary>
        public string RecommendedAction { get; set; } = string.Empty;

        /// <summary>Urgency: Low | Medium | High | Immediate</summary>
        [MaxLength(30)]
        public string Urgency { get; set; } = "Medium";

        [MaxLength(100)]
        public string ModelName { get; set; } = "gemini-2.5-flash";

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
